### ISSUE TITLE
Problem with mix.exs example

### ISSUE THREAD

**Issue by muhmi** [tsharju/elixir_locker#3]
Your examples asks to add:  `{:elixir_locker, "~>v0.1.3"}` to mix.exs but that causes:

``` bash
** (Version.InvalidRequirementError) ~>v0.1.3
    (elixir) lib/version.ex:121: Version.match?/2
    (elixir) lib/enum.ex:662: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:662: Enum.filter/2
    lib/hex/remote_converger.ex:79: Hex.RemoteConverger.check_package_req/3
    (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:537: Enum.each/2
    lib/hex/remote_converger.ex:68: Hex.RemoteConverger.check_input/2
```

You should remove the "v" character

**Comment by tsharju** [comment]
Oops... thanks for pointing this out. :) :+1:
